-- MySQL Script generated by MySQL Workbench
-- Wed Nov 30 22:19:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lockey_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lockey_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lockey_db` DEFAULT CHARACTER SET utf8 ;
USE `lockey_db` ;

-- -----------------------------------------------------
-- Table `lockey_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`User` (
  `id_usr` INT NOT NULL AUTO_INCREMENT,
  `nm_usr` VARCHAR(45) NOT NULL,
  `em_usr` VARCHAR(45) NOT NULL,
  `tel_usr` VARCHAR(45) NULL,
  `pwd_usr` VARCHAR(45) NOT NULL,
  `type_usr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usr`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_user_UNIQUE` ON `lockey_db`.`User` (`id_usr` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lockey_db`.`Wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`Wallet` (
  `id_wal` INT NOT NULL,
  `id_usr` INT NOT NULL,
  `nknm_wal` VARCHAR(45) NOT NULL,
  `nm_wal` VARCHAR(45) NOT NULL,
  `num_wal` VARCHAR(4) NOT NULL,
  `date_wal` DATE NOT NULL,
  PRIMARY KEY (`id_wal`),
  CONSTRAINT `fk_wallet_user`
    FOREIGN KEY (`id_usr`)
    REFERENCES `lockey_db`.`User` (`id_usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_wallet_user_idx` ON `lockey_db`.`Wallet` (`id_usr` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lockey_db`.`ShippingType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`ShippingType` (
  `id_shpgtype` INT NOT NULL,
  `nm_shpgtype` VARCHAR(45) NOT NULL,
  `time_shpgtype` TIME NOT NULL,
  PRIMARY KEY (`id_shpgtype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lockey_db`.`Shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`Shipping` (
  `trk_shpg` INT NOT NULL,
  `ownr_shpg` INT NOT NULL,
  `id_shpgtype` INT NOT NULL,
  `stat_shpg` INT NOT NULL,
  `dts_shpg` DATETIME NOT NULL DEFAULT NOW(),
  `dte_shpg` DATETIME NULL,
  `pr_shpg` DOUBLE NOT NULL,
  `wt_shpg` VARCHAR(45) NOT NULL,
  `dim_shpg` VARCHAR(45) NOT NULL,
  `id_wal` INT NOT NULL,
  PRIMARY KEY (`trk_shpg`),
  CONSTRAINT `fk_shipping_user`
    FOREIGN KEY (`ownr_shpg`)
    REFERENCES `lockey_db`.`User` (`id_usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipping_wallet`
    FOREIGN KEY (`id_wal`)
    REFERENCES `lockey_db`.`Wallet` (`id_wal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipping)shippingtype`
    FOREIGN KEY (`id_shpgtype`)
    REFERENCES `lockey_db`.`ShippingType` (`id_shpgtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `trk_shpg_UNIQUE` ON `lockey_db`.`Shipping` (`trk_shpg` ASC) VISIBLE;

CREATE INDEX `fk_shipping_user_idx` ON `lockey_db`.`Shipping` (`ownr_shpg` ASC) VISIBLE;

CREATE INDEX `fk_shipping_wallet_idx` ON `lockey_db`.`Shipping` (`id_wal` ASC) VISIBLE;

CREATE INDEX `fk_shipping)shippingtype_idx` ON `lockey_db`.`Shipping` (`id_shpgtype` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lockey_db`.`Locker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`Locker` (
  `id_lkr` INT NOT NULL,
  `nm_lkr` VARCHAR(45) NOT NULL,
  `dir_lkr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lkr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lockey_db`.`DoorType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`DoorType` (
  `id_drtype` INT NOT NULL,
  `nm_drtype` VARCHAR(45) NOT NULL,
  `hgt_drtype` VARCHAR(45) NOT NULL,
  `wd_drtype` VARCHAR(45) NOT NULL,
  `deep_drtype` VARCHAR(45) NOT NULL,
  `wt_drtype` VARCHAR(45) NULL,
  PRIMARY KEY (`id_drtype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lockey_db`.`Door`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`Door` (
  `id_door` INT NOT NULL AUTO_INCREMENT,
  `id_lkr` INT NOT NULL,
  `id_drtype` INT NOT NULL,
  `nm_door` VARCHAR(45) NOT NULL,
  `stat_door` INT NULL,
  PRIMARY KEY (`id_door`),
  CONSTRAINT `fk_door_locker`
    FOREIGN KEY (`id_lkr`)
    REFERENCES `lockey_db`.`Locker` (`id_lkr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_door_doortype`
    FOREIGN KEY (`id_drtype`)
    REFERENCES `lockey_db`.`DoorType` (`id_drtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_locker_idx` ON `lockey_db`.`Door` (`id_lkr` ASC) VISIBLE;

CREATE INDEX `fk_door_doortype_idx` ON `lockey_db`.`Door` (`id_drtype` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lockey_db`.`Shipping-Door`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`Shipping-Door` (
  `id_shpgdr` INT NOT NULL,
  `id_door` INT NOT NULL,
  `trk_shpg` INT NOT NULL,
  `edge_shpgdr` TINYINT(1) NOT NULL,
  `busy_shpgdr` TINYINT(1) NOT NULL DEFAULT 0,
  `nm_shpgdr` VARCHAR(45) NOT NULL,
  `em_shpgdr` VARCHAR(45) NOT NULL,
  `tel_shpgdr` VARCHAR(45) NULL,
  `qr_shpgdr` VARCHAR(45) NULL,
  PRIMARY KEY (`id_shpgdr`),
  CONSTRAINT `fk_shipping-door_shipping`
    FOREIGN KEY (`trk_shpg`)
    REFERENCES `lockey_db`.`Shipping` (`trk_shpg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipping-door_door`
    FOREIGN KEY (`id_door`)
    REFERENCES `lockey_db`.`Door` (`id_door`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_shipping-door_shipping_idx` ON `lockey_db`.`Shipping-Door` (`trk_shpg` ASC) VISIBLE;

CREATE INDEX `fk_shipping-door_door_idx` ON `lockey_db`.`Shipping-Door` (`id_door` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lockey_db`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`Report` (
  `id_rpt` INT NOT NULL,
  `id_usr` INT NOT NULL,
  `id_door` INT NOT NULL,
  `trk_shpg` INT NULL,
  `tit_rpt` VARCHAR(45) NOT NULL,
  `msg_rpt` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rpt`),
  CONSTRAINT `fk_report_user`
    FOREIGN KEY (`id_usr`)
    REFERENCES `lockey_db`.`User` (`id_usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_door`
    FOREIGN KEY (`id_door`)
    REFERENCES `lockey_db`.`Door` (`id_door`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_shipping`
    FOREIGN KEY (`trk_shpg`)
    REFERENCES `lockey_db`.`Shipping` (`trk_shpg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_report_user_idx` ON `lockey_db`.`Report` (`id_usr` ASC) VISIBLE;

CREATE INDEX `fk_report_door_idx` ON `lockey_db`.`Report` (`id_door` ASC) VISIBLE;

CREATE INDEX `fk_report_shipping_idx` ON `lockey_db`.`Report` (`trk_shpg` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lockey_db`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`Route` (
  `id_rte` INT NOT NULL,
  `id_usr` INT NOT NULL,
  `date_rte` DATETIME NOT NULL,
  `stat_rte` INT NOT NULL,
  PRIMARY KEY (`id_rte`),
  CONSTRAINT `fk_route_user`
    FOREIGN KEY (`id_usr`)
    REFERENCES `lockey_db`.`User` (`id_usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_route_user_idx` ON `lockey_db`.`Route` (`id_usr` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lockey_db`.`RouteDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lockey_db`.`RouteDetail` (
  `id_rtedtl` INT NOT NULL,
  `id_rte` INT NOT NULL,
  `id_lkr` INT NOT NULL,
  `ord_rtedtl` INT NOT NULL,
  PRIMARY KEY (`id_rtedtl`),
  CONSTRAINT `fk_routedetail_route`
    FOREIGN KEY (`id_rte`)
    REFERENCES `lockey_db`.`Route` (`id_rte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_routedetail_locker`
    FOREIGN KEY (`id_lkr`)
    REFERENCES `lockey_db`.`Locker` (`id_lkr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_routedetail_route_idx` ON `lockey_db`.`RouteDetail` (`id_rte` ASC) VISIBLE;

CREATE INDEX `fk_routedetail_locker_idx` ON `lockey_db`.`RouteDetail` (`id_lkr` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Database user
CREATE USER 'lockey_usr'@'%' IDENTIFIED BY 'lockey_pwd_issi_pz.';
GRANT insert,select,delete,update ON `lockey_db`.* TO 'lockey_usr'@'%';